name: flutter_super_state_example

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_super_state: ^0.2.0

flutter:
  uses-material-design: true
